package main.java.day11;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class GalaxyTest {

    @Test
    void getTotalPairsDistance() {
        String input = """
                ...#......
                .......#..
                #.........
                ..........
                ......#...
                .#........
                .........#
                ..........
                .......#..
                #...#.....
                """;
        Galaxy galaxy = new Galaxy(List.of(input.split("\\n")));
        assertEquals(374, galaxy.getTotalPairsDistance(2));
    }

    @Test
    void getTotalPairsDistanceWith10xExpansion() {
        String input = """
                ...#......
                .......#..
                #.........
                ..........
                ......#...
                .#........
                .........#
                ..........
                .......#..
                #...#.....
                """;
        Galaxy galaxy = new Galaxy(List.of(input.split("\\n")));
        assertEquals(1030, galaxy.getTotalPairsDistance(10));
    }

    @Test
    void getTotalPairsDistanceWith100xExpansion() {
        String input = """
                ...#......
                .......#..
                #.........
                ..........
                ......#...
                .#........
                .........#
                ..........
                .......#..
                #...#.....
                """;
        Galaxy galaxy = new Galaxy(List.of(input.split("\\n")));
        assertEquals(8410, galaxy.getTotalPairsDistance(100));
    }
}